# Copyright 2022 Hewlett Packard Enterprise Development LP
name: GitHub Actions CI

on: [push, pull_request]
jobs:
  ci:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        go: [ '1.17' ]
    name: Lint
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.51.0
      - run: make lint
